import type { Rarity, UpgradeDefinition } from "../models/types";

// Base weight per rarity; combined with per-upgrade dropWeight when rolling.
export const UPGRADE_RARITY_ODDS = {
	common: 0.65,
	rare: 0.3,
	legendary: 0.05,
} satisfies Record<Rarity, number>;

export const UPGRADE_BLUEPRINTS: UpgradeDefinition[] = [
	{
		id: "power-shot",
		name: "Power Shot",
		description: "Increase primary damage by 15% and +5% crit chance.",
		rarity: "common",
		category: "offense",
		maxStacks: 8,
		dropWeight: 1.1,
	},
	{
		id: "rapid-fire",
		name: "Rapid Fire",
		description: "Increase fire rate by 15%.",
		rarity: "common",
		category: "offense",
		maxStacks: 8,
		dropWeight: 1.1,
	},
	{
		id: "swift-projectiles",
		name: "Swift Projectiles",
		description: "Projectile speed up by 20%.",
		rarity: "common",
		category: "offense",
		maxStacks: 6,
		dropWeight: 1,
	},
	{
		id: "engine-tune",
		name: "Engine Tune",
		description: "Movement speed up by 10%.",
		rarity: "common",
		category: "utility",
		maxStacks: 6,
		dropWeight: 1,
	},
	{
		id: "plating",
		name: "Light Plating",
		description: "+1 max health and -8% incoming damage per stack.",
		rarity: "common",
		category: "defense",
		maxStacks: 5,
		dropWeight: 0.9,
	},
	{
		id: "sidecar",
		name: "Sidecar Shot",
		description: "+1 extra projectile with a slight spread.",
		rarity: "common",
		category: "offense",
		maxStacks: 3,
		dropWeight: 1,
	},
	{
		id: "pierce",
		name: "Piercing Rounds",
		description: "Projectiles pierce one additional target.",
		rarity: "common",
		category: "offense",
		maxStacks: 3,
		dropWeight: 1,
	},
	{
		id: "heavy-barrel",
		name: "Heavy Barrel",
		description:
			"+25% projectile size, +20% damage, +5% crit damage, -10% fire rate.",
		rarity: "common",
		category: "offense",
		maxStacks: 3,
		dropWeight: 0.9,
	},
	{
		id: "rebound",
		name: "Rebound",
		description: "Projectiles gain +2 ricochets; -5% speed per stack.",
		rarity: "common",
		category: "offense",
		maxStacks: 3,
		dropWeight: 0.9,
	},
	{
		id: "dash-sparks",
		name: "Dash Sparks",
		description: "Dashing detonates a close-range shrapnel burst.",
		rarity: "common",
		category: "utility",
		maxStacks: 3,
		dropWeight: 1,
	},
	{
		id: "held-charge",
		name: "Held Charge",
		description:
			"Hold fire to charge +80% damage; charged shots pierce through 3 foes.",
		rarity: "common",
		category: "offense",
		maxStacks: 3,
		dropWeight: 1,
	},
	{
		id: "shield-pickup",
		name: "XP Shield",
		description: "Collecting XP grants a 1-hit shield for 2s (cooldown).",
		rarity: "common",
		category: "defense",
		maxStacks: 3,
		dropWeight: 1,
	},
	{
		id: "magnet-coil",
		name: "Magnet Coil",
		description: "XP pulls from farther away and moves faster toward you.",
		rarity: "common",
		category: "utility",
		maxStacks: 3,
		dropWeight: 1,
	},
	{
		id: "stabilizers",
		name: "Stabilizers",
		description: "Reduce collision damage and knockback.",
		rarity: "common",
		category: "defense",
		maxStacks: 3,
		dropWeight: 0.9,
	},
	{
		id: "shrapnel",
		name: "Shrapnel",
		description: "Enemies you destroy spray forward a cone of fragments.",
		rarity: "rare",
		category: "offense",
		maxStacks: 2,
		dropWeight: 0.85,
	},
	{
		id: "kinetic-siphon",
		name: "Kinetic Siphon",
		description: "On kill, heal a small amount (cooldown).",
		rarity: "common",
		category: "defense",
		maxStacks: 3,
		dropWeight: 0.9,
	},
	{
		id: "prism-spread",
		name: "Prism Spread",
		description: "Tightens multi-shot spread and adds crit chance.",
		rarity: "rare",
		category: "offense",
		maxStacks: 2,
		dropWeight: 0.8,
	},
	{
		id: "momentum-feed",
		name: "Momentum Feed",
		description: "Moving builds up to +25% fire rate over sustained motion.",
		rarity: "rare",
		category: "utility",
		maxStacks: 2,
		dropWeight: 0.9,
	},
	{
		id: "split-shot",
		name: "Split Shot",
		description: "First hit splits into two shards for 50% damage.",
		rarity: "rare",
		category: "offense",
		maxStacks: 2,
		dropWeight: 0.9,
	},
	{
		id: "explosive-impact",
		name: "Explosive Impact",
		description: "Projectiles explode on hit for extra area damage.",
		rarity: "rare",
		category: "offense",
		maxStacks: 3,
		dropWeight: 1,
	},
	{
		id: "chain-arc",
		name: "Chain Arc",
		description:
			"On kill, arc lightning to the nearest enemy for bonus damage.",
		rarity: "rare",
		category: "offense",
		maxStacks: 2,
		dropWeight: 0.85,
	},
	{
		id: "heatseeker",
		name: "Heatseeker Rounds",
		description:
			"Projectiles gently home toward nearby enemies; stronger each stack.",
		rarity: "rare",
		category: "offense",
		maxStacks: 3,
		dropWeight: 0.85,
	},
	{
		id: "neutron-core",
		name: "Neutron Core",
		description:
			"Projectiles become heavy spheres that block enemy shots but move 40% slower.",
		rarity: "legendary",
		category: "defense",
		maxStacks: 1,
		dropWeight: 1,
	},
	{
		id: "glass-cannon",
		name: "Glass Cannon",
		description:
			"Deal +200% Damage, +10% crit chance, but max HP is capped at 1.",
		rarity: "legendary",
		category: "offense",
		maxStacks: 1,
		dropWeight: 0.8,
	},
	{
		id: "singularity-rounds",
		name: "Singularity Rounds",
		description:
			"Projectiles allow no knockback, but PULL enemies into the impact point.",
		rarity: "legendary",
		category: "utility",
		maxStacks: 1,
		dropWeight: 1,
	},
	{
		id: "bullet-hell",
		name: "Bullet Hell",
		description: "+300% Fire Rate. Accuracy -80%. Damage -40%.",
		rarity: "legendary",
		category: "offense",
		maxStacks: 1,
		dropWeight: 1,
	},
	{
		id: "blood-fuel",
		name: "Blood Fuel",
		description:
			"Killing enemies heals you. Firing weapons costs 2% of current HP.",
		rarity: "rare",
		category: "offense",
		maxStacks: 1,
		dropWeight: 0.5,
	},
	{
		id: "chain-reaction",
		name: "Volatile Compounds",
		description:
			"Enemies explode on death for 50% of their max HP in a small radius.",
		rarity: "rare",
		category: "offense",
		maxStacks: 5,
		dropWeight: 0.8,
	},
	{
		id: "quantum-tunneling",
		name: "Quantum Tunneling",
		description: "Projectiles travel through walls and obstacles effortlessly.",
		rarity: "rare",
		category: "utility",
		maxStacks: 1,
		dropWeight: 0.6,
	},
	{
		id: "berserk-module",
		name: "Berserk Module",
		description: "The lower your health, the faster you fire (up to +100%).",
		rarity: "rare",
		category: "offense",
		maxStacks: 3,
		dropWeight: 0.9,
	},
];

export const UPGRADE_CATALOG = UPGRADE_BLUEPRINTS;

export const getUpgradeDefinition = (id: string) =>
	UPGRADE_BLUEPRINTS.find((u) => u.id === id);
