import type { UpgradeDefinition } from "../models/types";

// Draw odds between rarity buckets. Use dropWeight inside the bucket.
export const UPGRADE_RARITY_ODDS = {
  common: 0.7,
  rare: 0.3,
};

export const UPGRADE_BLUEPRINTS: UpgradeDefinition[] = [
  {
    id: "power-shot",
    name: "Power Shot",
    description: "Increase primary damage by 15%.",
    rarity: "common",
    category: "offense",
    maxStacks: 8,
    dropWeight: 1.1,
  },
  {
    id: "rapid-fire",
    name: "Rapid Fire",
    description: "Increase fire rate by 15%.",
    rarity: "common",
    category: "offense",
    maxStacks: 8,
    dropWeight: 1.1,
  },
  {
    id: "swift-projectiles",
    name: "Swift Projectiles",
    description: "Projectile speed up by 20%.",
    rarity: "common",
    category: "offense",
    maxStacks: 6,
    dropWeight: 1,
  },
  {
    id: "engine-tune",
    name: "Engine Tune",
    description: "Movement speed up by 10%.",
    rarity: "common",
    category: "utility",
    maxStacks: 6,
    dropWeight: 1,
  },
  {
    id: "plating",
    name: "Light Plating",
    description: "+1 max health.",
    rarity: "common",
    category: "defense",
    maxStacks: 5,
    dropWeight: 0.9,
  },
  {
    id: "sidecar",
    name: "Sidecar Shot",
    description: "+1 extra projectile with a slight spread.",
    rarity: "common",
    category: "offense",
    maxStacks: 3,
    dropWeight: 0.9,
  },
  {
    id: "pierce",
    name: "Piercing Rounds",
    description: "Projectiles pierce one additional target.",
    rarity: "common",
    category: "offense",
    maxStacks: 3,
    dropWeight: 1,
  },
  {
    id: "heavy-barrel",
    name: "Heavy Barrel",
    description: "+25% projectile size and +20% damage, -10% fire rate.",
    rarity: "common",
    category: "offense",
    maxStacks: 3,
    dropWeight: 0.9,
  },
  {
    id: "rebound",
    name: "Rebound",
    description: "Projectiles bounce once and slow slightly.",
    rarity: "common",
    category: "offense",
    maxStacks: 3,
    dropWeight: 0.9,
  },
  {
    id: "dash-sparks",
    name: "Dash Sparks",
    description: "Dashing detonates a close-range shrapnel burst.",
    rarity: "common",
    category: "utility",
    maxStacks: 3,
    dropWeight: 1,
  },
  {
    id: "held-charge",
    name: "Held Charge",
    description: "Hold fire to charge +80% damage; charged shots pierce through 3 foes.",
    rarity: "common",
    category: "offense",
    maxStacks: 3,
    dropWeight: 1,
  },
  {
    id: "shield-pickup",
    name: "XP Shield",
    description: "Collecting XP grants a 1-hit shield for 2s (cooldown).",
    rarity: "common",
    category: "defense",
    maxStacks: 3,
    dropWeight: 1,
  },
  {
    id: "magnet-coil",
    name: "Magnet Coil",
    description: "XP pulls from farther away and moves faster toward you.",
    rarity: "common",
    category: "utility",
    maxStacks: 3,
    dropWeight: 1,
  },
  {
    id: "stabilizers",
    name: "Stabilizers",
    description: "Reduce collision damage and knockback.",
    rarity: "common",
    category: "defense",
    maxStacks: 3,
    dropWeight: 0.9,
  },
  {
    id: "shrapnel",
    name: "Shrapnel",
    description: "Enemies you destroy spray forward a cone of fragments.",
    rarity: "rare",
    category: "offense",
    maxStacks: 2,
    dropWeight: 0.85,
  },
  {
    id: "kinetic-siphon",
    name: "Kinetic Siphon",
    description: "On kill, heal a small amount (cooldown).",
    rarity: "common",
    category: "defense",
    maxStacks: 3,
    dropWeight: 0.9,
  },
  {
    id: "prism-spread",
    name: "Prism Spread",
    description: "Tightens multi-shot spread and adds crit chance.",
    rarity: "rare",
    category: "offense",
    maxStacks: 2,
    dropWeight: 0.8,
  },
  {
    id: "momentum-feed",
    name: "Momentum Feed",
    description: "Moving builds up to +25% fire rate over sustained motion.",
    rarity: "rare",
    category: "utility",
    maxStacks: 2,
    dropWeight: 0.9,
  },
  {
    id: "split-shot",
    name: "Split Shot",
    description: "First hit splits into two shards for 50% damage.",
    rarity: "rare",
    category: "offense",
    maxStacks: 2,
    dropWeight: 0.9,
  },
  {
    id: "explosive-impact",
    name: "Explosive Impact",
    description: "Projectiles explode on hit for extra area damage.",
    rarity: "rare",
    category: "offense",
    maxStacks: 3,
    dropWeight: 1,
  },
  {
    id: "chain-arc",
    name: "Chain Arc",
    description: "On kill, arc lightning to the nearest enemy for bonus damage.",
    rarity: "rare",
    category: "offense",
    maxStacks: 2,
    dropWeight: 0.85,
  },
  {
    id: "heatseeker",
    name: "Heatseeker Rounds",
    description: "Projectiles gently home toward nearby enemies; stronger each stack.",
    rarity: "rare",
    category: "offense",
    maxStacks: 3,
    dropWeight: 0.85,
  },
];

export const UPGRADE_CATALOG = UPGRADE_BLUEPRINTS;

export const getUpgradeDefinition = (id: string) =>
  UPGRADE_BLUEPRINTS.find((u) => u.id === id);
