// Game state exports
export {
    GameSettingsRepository,
    // Type exports
    type PlayerStats,
    type ChargeState,
    type CapacitorConfig,
    type AfterimageConfig,
    type DashSparkConfig,
    type ShieldConfig,
    type ExplosiveConfig,
    type SplitConfig,
    type ChainArcConfig,
    type KineticConfig,
    type MomentumConfig,
    type SpreadConfig,
    type HomingConfig,
    type MagnetConfig,
    type StabilizerConfig,
    type PlatingConfig,
    type ShrapnelConfig,
    type NeutronCoreConfig,
    type SingularityConfig,
    type BulletHellConfig,
    type BloodFuelConfig,
    type ChainReactionConfig,
    type QuantumConfig,
    type BerserkConfig,
    type UpgradeState,
    type GameSettingsSnapshot,
    // Factory functions
    createDefaultPlayerStats,
    createDefaultChargeState,
    createDefaultCapacitorConfig,
    createDefaultAfterimageConfig,
    createDefaultDashSparkConfig,
    createDefaultShieldConfig,
    createDefaultExplosiveConfig,
    createDefaultSplitConfig,
    createDefaultChainArcConfig,
    createDefaultKineticConfig,
    createDefaultMomentumConfig,
    createDefaultSpreadConfig,
    createDefaultHomingConfig,
    createDefaultMagnetConfig,
    createDefaultStabilizerConfig,
    createDefaultPlatingConfig,
    createDefaultShrapnelConfig,
    createDefaultNeutronCoreConfig,
    createDefaultSingularityConfig,
    createDefaultBulletHellConfig,
    createDefaultBloodFuelConfig,
    createDefaultChainReactionConfig,
    createDefaultQuantumConfig,
    createDefaultBerserkConfig,
} from "./GameSettingsRepository";
